server:
  port: 8090

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5433/airport
    username: postgres
    password: root

---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        temp:
          use-jdbc-metadata-defaults: false

---
spring:
  flyway:
    baseline-on-migrate: true

---
spring:
  config:
    import: classpath:routing-service.yaml